# https://towardsdatascience.com/a-guide-to-conda-environments-bc6180fc533
name: ai4e
channels:
  - conda-forge
  - rapidsai
  - nvidia
  - pytorch
  - anaconda
dependencies:
  - python=3.8
  - numpy==1.17.2
  - scipy==1.3.1
  - pandas==0.25.1
  - scikit-learn==0.21.2
  - transformers==3.5.1
  - tensorflow-gpu==2.2.0
  - dask[complete]==2.30.0
  - ipython==7.19.0
  - pytorch==1.7.0
  - torchvision==0.8.1
  - jupyterlab==2.2.9
  - xgboost==1.2.0
  - pip:
    - datasets==1.1.3
